// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Click Links', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Click Links', async function() {
    await driver.get("http://abm-test.goregstr.com/login")
    await driver.manage().window().setRect({ width: 1559, height: 769 })
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("esilvas@gobrangus.com")
    await driver.findElement(By.name("password")).sendKeys("qNFh$Vv6SC_/$xk")
    await driver.findElement(By.css(".btn-block")).click()
    await driver.findElement(By.linkText("Animales")).click()
    await driver.findElement(By.linkText("Animales")).click()
    await driver.findElement(By.linkText("Facturación")).click()
    await driver.findElement(By.css("#invoices-nav-item > span")).click()
    await driver.findElement(By.linkText("Cría")).click()
    await driver.findElement(By.id("nba-nav-item")).click()
    await driver.findElement(By.linkText("Membership ABM")).click()
    await driver.findElement(By.id("create-a-member-nav-item")).click()
    await driver.findElement(By.css(".account")).click()
    await driver.findElement(By.css(".fa-sign-out-alt")).click()
  })
})
