// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('dashboard top search', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('dashboard top search', async function() {
    await driver.get("http://abm-test.goregstr.com/login")
    driver.manage().window().maximize();

    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("esilvas@gobrangus.com")
    await driver.findElement(By.name("password")).sendKeys("qNFh$Vv6SC_/$xk")
    await driver.findElement(By.css(".btn-block")).click()
    await new Promise(r => setTimeout(r, 2000));

    const elements = await driver.findElements(By.linkText("🇺🇸"))
    if(elements.length > 0){
      console.log("Clicked on US")
      await driver.findElement(By.linkText("🇺🇸")).click()
      await driver.findElement(By.css(".locale > li:nth-child(1) > .dropdown-item")).click()
      {
        const elements = await driver.findElements(By.xpath("//span[contains(.,\'ALL ANIMALS\')]"))
        assert(elements.length)
      }
      await new Promise(r => setTimeout(r, 3000));
      await driver.findElement(By.linkText("🇺🇸")).click()
      await driver.findElement(By.css("li:nth-child(2) .ml-2")).click()
      {
        const elements = await driver.findElements(By.xpath("//span[contains(.,\'ALL ANIMALS ABM\')]"))
        assert(elements.length)
      }
      await new Promise(r => setTimeout(r, 3000));
      await driver.findElement(By.css(".account")).click()
      await driver.findElement(By.linkText("Salir")).click()  

    }else{
      console.log("Clicked on MX")
      await driver.findElement(By.linkText("🇲🇽")).click()
      await driver.findElement(By.css("li:nth-child(2) .ml-2")).click()
      {
        const elements = await driver.findElements(By.xpath("//span[contains(.,\'ALL ANIMALS ABM\')]"))
        assert(elements.length)
      }
      await new Promise(r => setTimeout(r, 3000));
      await driver.findElement(By.linkText("🇲🇽")).click()
      await driver.findElement(By.css(".locale > li:nth-child(1) > .dropdown-item")).click()
      {
        const elements = await driver.findElements(By.xpath("//span[contains(.,\'ALL ANIMALS\')]"))
        assert(elements.length)
      }
      await new Promise(r => setTimeout(r, 3000));
      await driver.findElement(By.css(".account")).click()
      await driver.findElement(By.linkText("Logout")).click()  
    }      
  })
})
