// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('dashboard top search', function() {
  this.timeout(60000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 6) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('dashboard top search member', async function() {

    await driver.get("http://abm-test.goregstr.com/login")
    driver.manage().window().maximize();

    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("esilvas@gobrangus.com")
    await driver.findElement(By.name("password")).sendKeys("qNFh$Vv6SC_/$xk")
    await driver.findElement(By.css(".btn-block")).click()

    await new Promise(r => setTimeout(r, 2000));
    await driver.findElement(By.id("search")).click()
    await driver.findElement(By.id("search")).sendKeys("65800")
    await new Promise(r => setTimeout(r, 2000));

    // Issue #1 : Selenium is not recognizing the <ul><li> values 
    //await driver.findElement(By.xpath('//li[last()]')).click()

    // Issue #2 : The search opens another window - check how to proceed
    //vars["windowHandles"] = await driver.getAllWindowHandles()
    //vars["win6232"] = await waitForWindow(6000)
    //await driver.switchTo().window(vars["win6232"])

    await driver.findElement(By.css(".account")).click()
    await driver.findElement(By.linkText("Salir")).click()
  })
})
