// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Click Links', function() {
  this.timeout(60000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Click Links', async function() {
    await driver.get("http://abm-test.goregstr.com/login")
    //await driver.manage().window().setRect({ width: 1559, height: 769 }) remove
    driver.manage().window().maximize();
    await new Promise(r => setTimeout(r, 2000));
    
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("esilvas@gobrangus.com")
    await driver.findElement(By.name("password")).sendKeys("qNFh$Vv6SC_/$xkx") // wrong password
    await driver.findElement(By.css(".btn-block")).click()
    await new Promise(r => setTimeout(r, 2000));
    {
        const elements = await driver.findElements(By.xpath("//strong[contains(.,'Estas credenciales no coinciden con nuestros registros.')]"))
        assert(elements.length)
    }
  })
})
