// Generated by Selenium IDE
const {Builder,By,Key} = require('selenium-webdriver'); // selenium web driver
const assert = require('assert'); // assertion package
var should = require('chai').should(); // chai assertion package - should style ( if you want to use expect style just dont add .should )

function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));  // await sleep(i * 1000);
}

async function example(){

    // launch the browser 
    let driver = await new Builder().forBrowser('chrome').build();

    // navigate to our application
    await driver.get("https://lambdatest.github.io/sample-todo-app/");

    //await new Promise(r => setTimeout(r, 2000)); (or)
    await sleep(1000);

    // add a todo
    await driver.findElement(By.id('sampletodotext')).sendKeys('Learn Selenium',Key.RETURN);
    await sleep(2000);

    /** assertion to check if the text "Learn Selenium" was added **/

    // find the last item on the list and retrieve it // retrieves the last item added to the list 
    let todoText = await driver.findElement(By.xpath('//li[last()]')).getText().then(function(value){
        return value
    })
    
    // actual versus expected - checks the matches
    //assert.strictEqual(todoText,'Learn Selenium');

    // assert using chai should  ( should uses the value that you want to validate )
    todoText.should.equal('Learn Selenium');


    await sleep(1000);

    // close the browser
    await driver.quit();


}
// call to execute function above
example();