// Generated by Selenium IDE
const {Builder,By,Key} = require('selenium-webdriver');
const assert = require('assert')

function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));  // await sleep(i * 1000);
}

async function example(){

    // launch the browser 
    let driver = await new Builder().forBrowser('chrome').build();


    // navigate to our application
    await driver.get("http://abm-test.goregstr.com/login")
    //await driver.manage().window().setRect({ width: 1096, height: 966 })
    await driver.findElement(By.name("email")).click()
    await sleep(1000);
    await driver.findElement(By.name("email")).sendKeys("esilvas@gobrangus.com")
    await sleep(1000);
    await driver.findElement(By.name("password")).sendKeys("qNFh$Vv6SC_/$xk")
    await sleep(1000);
    await driver.findElement(By.css(".btn-block")).click()
    {
      const elements = await driver.findElements(By.xpath("//span[contains(.,\'Bienvenido Emilio Silvas\')]"))
      //assert(elements.length)
      console.log(elements)
      //assert(elements.length() > 0);
      console.log('output')
    }
    // add a todo

    // close the browser


}
// call to execute function above
example()